import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FirebaseProvider } from "@/app/providers/firebase-provider";
import { AuthProvider } from "@/app/providers/firebase-auth-provider";
import QueryProvider from "./providers/query-provider";
import { RepositoryProvider } from "./providers/repository-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <FirebaseProvider>
          <AuthProvider>
            <RepositoryProvider>
              <QueryProvider>
                {children}
              </QueryProvider>
            </RepositoryProvider>
          </AuthProvider>
        </FirebaseProvider>
      </body>
    </html>
  );
}
