import { DO_NOT_USE_OR_YOU_WILL_BE_FIRED_CALLBACK_REF_RETURN_VALUES } from "react";
import { YArrayEvent } from "yjs";
import * as Y from "yjs";

class BaseItem {
  // unique node id generated by firestore
  id: string = "";
  // node main text--task headline or tag name
  title: string;
  // node content--task description
  content: string;
  // obviously
  created: number;
  lastUpdate: number;
  userId: string;

  //so unfortunate that we can't just put this in the property definition
  // but we need to use the constructor to set the default value
  constructor(_title : string, _userId : string, _content? : string) {
    this.title = _title;
    this.userId = _userId;
    this.content = _content || "";
    this.created = Date.now();
    this.lastUpdate = Date.now();
  }
}

export class Task extends BaseItem {
  type: "Task" = "Task";
  // task currently complete?
  completed: boolean = false;
  tagIds: string[] = []; // Array of tag IDs
  dueDate?: Date; // Optional due date
}

export class Tag extends BaseItem {
  type: "Tag" = "Tag";
  color?: string;
}

export type GTDItem = Task | Tag;

export type DatabaseItem = {
  state: GTDItem;
  history: Y.Doc;
}

